function init(self)

	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)

	if message_id == hash("walk-hero") then
		
	end

	if message_id == hash("stay-hero") then

	end
	
	if message_id == hash("open-gui") then

	end
	
	if message_id == hash("call") then

	end

	if message_id == hash("open-radio") then

	end
	
	if message_id == hash("search-item") then

	end
end
