function init(self)
	self.obj1 = gui.get_node("obj1")
	self.obj2 = gui.get_node("obj2")

	gui.set_enabled(self.obj1, false)
	gui.set_enabled(self.obj2, false)
end

function on_message(self, message_id, message, sender)
	if message_id == hash("lvl2obj1") then
		gui.set_enabled(self.obj1, true)
	end

	if message_id == hash("lvl2obj2") then
		gui.set_enabled(self.obj2, true)
	end
	
	if message_id == hash("reset") then
		gui.set_enabled(self.obj1, false)
		gui.set_enabled(self.obj2, false)
	end
end